### ISSUE TITLE
too many quality selection options

### ISSUE THREAD

**Issue by muneebhussain15** [ddurdle/GoogleDrive-VideoStream_extra#10]
Hello,

I got these many options while trying to use google transcoding options for emby

is this normal? 

doesnt google drive only give 1080, 720, 480 and 360?

![image](https://user-images.githubusercontent.com/15520829/56364412-e81cb780-6207-11e9-9c74-1a8f86cc8d22.png)

**Comment by ddurdle** [comment]
These have nothing to do with the plugin.  The plugin will use 4k,1080p, 720p, 480p
