### ISSUE TITLE
ffprobe fails

### ISSUE THREAD

**Issue by Thomvh** [ddurdle/GoogleDrive-VideoStream_extra#3]
When trying to run your transcoder scripts ffmpeg throws up an error and either the audio doesn't work or it plays the commentary track.

> *** Error Report ***
> 	Version: 3.5.3.0
> 	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
> 	Operating system: Unix 4.15.0.36
> 	64-Bit OS: True
> 	64-Bit Process: True
> 	User Interactive: True
> 	Processor count: 2
> 	Program data path: /var/lib/emby
> 	Application directory: /opt/emby-server/system
> 	System.Exception: ffprobe failed for "http://url:9988/default.py?mode=video&username=username&filename=filename&title=movie.mkv" - streams and format are both null.
> 	   at Emby.Server.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, VideoType videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
> 	   at Emby.Server.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, VideoType videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
> 	   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
> 	   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
> 	System.Exception
> 	   at Emby.Server.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, VideoType videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
> 	   at Emby.Server.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, VideoType videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
> 	   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
> 	   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

**Comment by Thomvh** [comment]
I've fixed that error. But now nothing plays anymore for some reason. 

The /tmp/transcode.log looks like this:

> passed in  -decoders
> m3u8 output file , channel
> running LIVETV /opt/emby-server/bin//ffmpeg.oem   -decoders
> 
> running LIVETV /opt/emby-server/bin//ffmpeg.oem   -decoders
> 
> passed in  -encoders
> m3u8 output file , channel
> running LIVETV /opt/emby-server/bin//ffmpeg.oem   -encoders
> 
> running LIVETV /opt/emby-server/bin//ffmpeg.oem   -encoders
> 
> passed in  -protocols
> m3u8 output file , channel
> running LIVETV /opt/emby-server/bin//ffmpeg.oem   -protocols
> 
> running LIVETV /opt/emby-server/bin//ffmpeg.oem   -protocols
> 
> passed in  -i "" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format
> running /opt/emby-server/bin//ffprobe.oem   -i "" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format
> ffprobe version 4.0.2-emby_2018_09_13 Copyright (c) 2007-2018 the FFmpeg developers
>   built with gcc 6.3.0 (crosstool-NG crosstool-ng-1.23.0)
>   configuration: --cc=x86_64-pc-linux-gnu-gcc --arch=x86_64 --prefix=/home/embybuilder/Buildbot/x64/ffmpeg-x64/staging --pkg-config=pkg-config --disable-doc --disable-ffplay --disable-vdpau --disable-xlib --enable-fontconfig --enable-gnutls --enable-gpl --enable-iconv --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libx264 --enable-libzvbi --enable-version3 --disable-decoders --disable-encoders --enable-decoder=aac --enable-decoder=aac_fixed --enable-decoder=aac_latm --enable-decoder=ac3 --enable-decoder=ac3_fixed --enable-decoder=alac --enable-decoder=apng --enable-decoder=ass --enable-decoder=ayuv --enable-decoder=bmp --enable-decoder=dca --enable-decoder=dirac --enable-decoder=dvbsub --enable-decoder=dvdsub --enable-decoder=eac3 --enable-decoder=flac --enable-decoder=gif --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=huffyuv --enable-decoder=mjpeg --enable-decoder=mlp --enable-decoder=mov_text --enable-decoder=mp3 --enable-decoder=mp3float --enable-decoder=mpeg4 --enable-decoder=opus --enable-decoder=pcm_alaw --enable-decoder=pcm_bluray --enable-decoder=pcm_dvd --enable-decoder=pcm_f16le --enable-decoder=pcm_f24le --enable-decoder=pcm_f32be --enable-decoder=pcm_f32le --enable-decoder=pcm_f64be --enable-decoder=pcm_f64le --enable-decoder=pcm_lxf --enable-decoder=pcm_mulaw --enable-decoder=pcm_s16be --enable-decoder=pcm_s16be_planar --enable-decoder=pcm_s16le --enable-decoder=pcm_s16le_planar --enable-decoder=pcm_s24be --enable-decoder=pcm_s24daud --enable-decoder=pcm_s24le --enable-decoder=pcm_s24le_planar --enable-decoder=pcm_s32be --enable-decoder=pcm_s32le --enable-decoder=pcm_s32le_planar --enable-decoder=pcm_s64be --enable-decoder=pcm_s64le --enable-decoder=pcm_s8 --enable-decoder=pcm_s8_planar --enable-decoder=pcm_u16be --enable-decoder=pcm_u16le --enable-decoder=pcm_u24be --enable-decoder=pcm_u24le --enable-decoder=pcm_u32be --enable-decoder=pcm_u32le --enable-decoder=pcm_u8 --enable-decoder=pcm_zork --enable-decoder=pgssub --enable-decoder=png --enable-decoder=r210 --enable-decoder=rawvideo --enable-decoder=ssa --enable-decoder=subrip --enable-decoder=srt --enable-decoder=text --enable-decoder=theora --enable-decoder=truehd --enable-decoder=v210 --enable-decoder=v210x --enable-decoder=v308 --enable-decoder=v408 --enable-decoder=v410 --enable-decoder=vorbis --enable-decoder=vp8 --enable-decoder=vp9 --enable-decoder=webp --enable-decoder=webvtt --enable-decoder=wmalossless --enable-decoder=wmapro --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=wmavoice --enable-decoder=wmv1 --enable-decoder=wmv2 --enable-decoder=wmv3 --enable-decoder=wmv3image --enable-decoder=y41p --enable-decoder=yuv4 --enable-decoder=zero12v --enable-encoder=aac --enable-encoder=ac3 --enable-encoder=ac3_fixed --enable-encoder=ass --enable-encoder=dvbsub --enable-encoder=dvdsub --enable-encoder=flac --enable-encoder=libmp3lame --enable-encoder=libopus --enable-encoder=libtheora --enable-encoder=libvorbis --enable-encoder=libwebp --enable-encoder=libx264 --enable-encoder=mjpeg --enable-encoder=mov_text --enable-encoder=png --enable-encoder=srt --enable-encoder=ssa --enable-encoder=subrip --enable-encoder=text --enable-encoder=webvtt --enable-libsmbclient --enable-decoder=mp1 --enable-decoder=mp2 --enable-decoder=mpegvideo --enable-decoder=mpeg1video --enable-decoder=mpeg2video --enable-decoder=vc1 --enable-cuda --enable-cuvid --enable-nvenc --enable-vaapi --enable-decoder=h264_cuvid --enable-decoder=hevc_cuvid --enable-decoder=mjpeg_cuvid --enable-decoder=mpeg1_cuvid --enable-decoder=mpeg2_cuvid --enable-decoder=mpeg4_cuvid --enable-decoder=vc1_cuvid --enable-decoder=vp8_cuvid --enable-decoder=vp9_cuvid --enable-encoder=h264_nvenc --enable-encoder=h264_vaapi --enable-encoder=hevc_nvenc --enable-encoder=hevc_vaapi --enable-encoder=mjpeg_vaapi --enable-cross-compile --cross-prefix=x86_64-pc-linux-gnu- --extra-libs='-ldl -lexpat -lfreetype -lfribidi -lfontconfig -liconv -lpng -luuid -lz -lvorbis -logg -lnettle -lhogweed -lgmp -laddns-samba4 -lasn1util-samba4 -lauthkrb5-samba4 -lCHARSET3-samba4 -lcliauth-samba4 -lcli-cldap-samba4 -lcli-ldap-common-samba4 -lcli-nbt-samba4 -lcli-smb-common-samba4 -lcom_err -lcommon-auth-samba4 -ldbwrap-samba4 -ldcerpc-binding -ldcerpc-samba-samba4 -lflag-mapping-samba4 -lgenrand-samba4 -lgensec-samba4 -lgse-samba4 -lgssapi_krb5 -llibcli-lsa3-samba4 -llibsmb-samba4 -linterfaces-samba4 -liov-buf-samba4 -lk5crypto -lkrb5 -lkrb5samba-samba4 -lkrb5support -lldb -lldbsamba-samba4 -lmessages-dgm-samba4 -lmessages-util-samba4 -lmsghdr-samba4 -lmsrpc3-samba4 -lndr -lndr-krb5pac -lndr-nbt -lndr-samba-samba4 -lndr-standard -lreplace-samba4 -lsamba-cluster-support-samba4 -lsamba-credentials -lsamba-debug-samba4 -lsamba-errors -lsamba-hostconfig -lsamba-modules-samba4 -lsamba-security-samba4 -lsamba-sockets-samba4 -lsamba-util -lsamba3-util-samba4 -lsamdb -lsamdb-common-samba4 -lsecrets3-samba4 -lserver-id-db-samba4 -lserver-role-samba4 -lsmbconf -lsmbd-shim-samba4 -lsmb-transport-samba4 -lsocket-blocking-samba4 -lsys-rw-samba4 -ltalloc -ltalloc-report-samba4 -ltdb -ltdb-wrap-samba4 -ltevent -ltevent-util -ltime-basic-samba4 -lutil-cmdline-samba4 -lutil-reg-samba4 -lutil-setid-samba4 -lutil-tdb-samba4 -lwbclient -lwinbind-client-samba4 -ldrm' --target-os=linux --enable-shared --disable-static
>   libavutil      56. 14.100 / 56. 14.100
>   libavcodec     58. 18.100 / 58. 18.100
>   libavformat    58. 12.100 / 58. 12.100
>   libavdevice    58.  3.100 / 58.  3.100
>   libavfilter     7. 16.100 /  7. 16.100
>   libswscale      5.  1.100 /  5.  1.100
>   libswresample   3.  1.100 /  3.  1.100
>   libpostproc    55.  1.100 / 55.  1.100
> Input #0, matroska,webm, from '':
>   Metadata:
>     encoder         : libebml v1.0.0 + libmatroska v1.0
>   Duration: 01:24:50.46, start: 0.000000, bitrate: 11060 kb/s
>     Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
>     Stream #0:1(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
> {
>     "streams": [
>         {
>             "index": 0,
>             "codec_name": "h264",
>             "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
>             "profile": "High",
>             "codec_type": "video",
>             "codec_time_base": "1001/48000",
>             "codec_tag_string": "[0][0][0][0]",
>             "codec_tag": "0x0000",
>             "width": 1920,
>             "height": 1080,
>             "coded_width": 1920,
>             "coded_height": 1088,
>             "has_b_frames": 2,
>             "sample_aspect_ratio": "1:1",
>             "display_aspect_ratio": "16:9",
>             "pix_fmt": "yuv420p",
>             "level": 41,
>             "chroma_location": "left",
>             "field_order": "progressive",
>             "refs": 1,
>             "is_avc": "true",
>             "nal_length_size": "4",
>             "r_frame_rate": "24000/1001",
>             "avg_frame_rate": "24000/1001",
>             "time_base": "1/1000",
>             "start_pts": 0,
>             "start_time": "0.000000",
>             "bits_per_raw_sample": "8",
>             "disposition": {
>                 "default": 1,
>                 "dub": 0,
>                 "original": 0,
>                 "comment": 0,
>                 "lyrics": 0,
>                 "karaoke": 0,
>                 "forced": 0,
>                 "hearing_impaired": 0,
>                 "visual_impaired": 0,
>                 "clean_effects": 0,
>                 "attached_pic": 0,
>                 "timed_thumbnails": 0
>             },
>             "tags": {
>                 "language": "eng"
>             }
>         },
>         {
>             "index": 1,
>             "codec_name": "dts",
>             "codec_long_name": "DCA (DTS Coherent Acoustics)",
>             "profile": "DTS",
>             "codec_type": "audio",
>             "codec_time_base": "1/48000",
>             "codec_tag_string": "[0][0][0][0]",
>             "codec_tag": "0x0000",
>             "sample_fmt": "fltp",
>             "sample_rate": "48000",
>             "channels": 6,
>             "channel_layout": "5.1(side)",
>             "bits_per_sample": 0,
>             "r_frame_rate": "0/0",
>             "avg_frame_rate": "0/0",
>             "time_base": "1/1000",
>             "start_pts": 0,
>             "start_time": "0.000000",
>             "bit_rate": "768000",
>             "disposition": {
>                 "default": 1,
>                 "dub": 0,
>                 "original": 0,
>                 "comment": 0,
>                 "lyrics": 0,
>                 "karaoke": 0,
>                 "forced": 0,
>                 "hearing_impaired": 0,
>                 "visual_impaired": 0,
>                 "clean_effects": 0,
>                 "attached_pic": 0,
>                 "timed_thumbnails": 0
>             },
>             "tags": {
>                 "language": "eng"
>             }
>         }
>     ],
>     "chapters": [
> 
>     ],
>     "format": {
>         "filename": "",
>         "nb_streams": 2,
>         "nb_programs": 0,
>         "format_name": "matroska,webm",
>         "format_long_name": "Matroska / WebM",
>         "start_time": "0.000000",
>         "duration": "5090.460000",
>         "size": "7038023997",
>         "bit_rate": "11060727",
>         "probe_score": 100,
>         "tags": {
>             "encoder": "libebml v1.0.0 + libmatroska v1.0"
>         }
>     }
> }
> passed in  -noaccurate_seek -f matroska,webm -i "" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af volume=2 -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 6 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list /u01/emby-transcode/transcoding-temp/dda166c6a2150be763d6a1186d3cfcb5.m3u8 -y /u01/emby-transcode/transcoding-temp/dda166c6a2150be763d6a1186d3cfcb5%d.ts
> AUDIO SELECTION 1
> URL = ,  -noaccurate_seek -f mp4 -i "&preferred_quality=0&override=true" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -copyts -vsync -1 -codec:a:0 copy -copypriorss:a:0 0 -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 6 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list /u01/emby-transcode/transcoding-temp/dda166c6a2150be763d6a1186d3cfcb5.m3u8 -y /u01/emby-transcode/transcoding-temp/dda166c6a2150be763d6a1186d3cfcb5%d.ts

**Comment by ddurdle** [comment]
Not sure if your log was edited or it is missing data.

**Comment by Thomvh** [comment]
I edited out my URL for obvious reasons. But that's all I edited.

Op wo 24 okt. 2018 00:53 schreef ddurdle <notifications@github.com>:

**Comment by Thomvh** [comment]
And I also get this error in Videostream

```----------------------------------------
Exception happened during processing of request from ('ip', 56946)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/u01/Python-GoogleDrive-VideoStream/resources/libgui/webgui.py", line 226, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by ddurdle** [comment]
Which device are you playing back with?

**Comment by Thomvh** [comment]
Testing via Google Chrome.

Op wo 24 okt. 2018 15:00 schreef ddurdle <notifications@github.com>:

**Comment by ddurdle** [comment]
Try copying the config.cfg from the transcoding directory to
/opt/emby-server/bin.  I believe that might be the key issue.

If that doesn't work, it might be the fact that google transcode streams
has issues with ffmpeg provided with emby 3.5.2 when playing back in web
and android (but doesn't affect roku or ios).  If that is the case, you
will need to retrieve a copy of the /opt/emby-server/lib and ffmpeg +
ffprobe from a known good emby (such as 3.3.1.12), place the lib folder as
/opt/emby-server/lib.332 and ffmpeg and ffprobe in /opt/emby-server/bin as
ffmpeg.oem.332 and ffprobe.oem.332 -- making it line up with the paths
noted in variable FFMPEG_OEM_332 in the config.cfg.  Then change the
parameter in the config.cfg file ALT_FFMPEG_DETERMINATOR variable to => '';

**Comment by Thomvh** [comment]
I've tried that. It doesn't solve anything, unfortunately. 

Transcoder.log:

```passed in  -decoders
m3u8 output file , channel
running LIVETV /opt/emby-server/bin//ffmpeg.oem   -decoders

running LIVETV /opt/emby-server/bin//ffmpeg.oem   -decoders

passed in  -encoders
m3u8 output file , channel
running LIVETV /opt/emby-server/bin//ffmpeg.oem   -encoders

running LIVETV /opt/emby-server/bin//ffmpeg.oem   -encoders

passed in  -protocols
m3u8 output file , channel
running LIVETV /opt/emby-server/bin//ffmpeg.oem   -protocols

running LIVETV /opt/emby-server/bin//ffmpeg.oem   -protocols

passed in  -noaccurate_seek -f matroska,webm -i "http://url:9988/default.py?mode=video&username=username&filename=1FeFWTf6VuZmqFOMffQneapsv61M0EwUo&title=Phantom+Halo+2014.mkv" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -copyts -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af volume=2 -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 6 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list /u01/emby-transcode/transcoding-temp/811e227f557d31ca1c651946ca5efd37.m3u8 -y /u01/emby-transcode/transcoding-temp/811e227f557d31ca1c651946ca5efd37%d.ts
AUDIO SELECTION 1
URL = http://url:9988/default.py?mode=video&username=username&filename=1FeFWTf6VuZmqFOMffQneapsv61M0EwUo&title=Phantom+Halo+2014.mkv,  -noaccurate_seek -f mp4 -i "http://smallbox.t97.nl:9988/default.py?mode=video&username=username&filename=1FeFWTf6VuZmqFOMffQneapsv61M0EwUo&title=Phantom+Halo+2014.mkv&preferred_quality=0&override=true" -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -copyts -vsync -1 -codec:a:0 copy -copypriorss:a:0 0 -f segment -max_delay 5000000 -avoid_negative_ts disabled -map_metadata -1 -map_chapters -1 -start_at_zero -segment_time 6 -individual_header_trailer 0 -break_non_keyframes 1 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list /u01/emby-transcode/transcoding-temp/811e227f557d31ca1c651946ca5efd37.m3u8 -y /u01/emby-transcode/transcoding-temp/811e227f557d31ca1c651946ca5efd37%d.ts
```

**Comment by ddurdle** [comment]
Are you able to open the URL for playback in VLC?

**Comment by ddurdle** [comment]
Also, is your transcoding directory really
/u01/emby-transcode/transcoding-temp/?
Make sure this matches in emby transcoding settings.

**Comment by Thomvh** [comment]
Yeah playback in vlc with
"http:/url:9988/default.py?mode=video&username=username&filename=12hSkLQZASTLUjuJJDGIhlLl6loiJ-EUC&title=2+Fast+2+Furious+2003.mkv&preferred_quality=0&override=true"
as url plays fine!

Op wo 24 okt. 2018 om 18:54 schreef ddurdle <notifications@github.com>:

**Comment by Thomvh** [comment]
I'm also seeing this again:```
----------------------------------------
Exception happened during processing of request from ('92.117.175.68', 51586)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/u01/Python-GoogleDrive-VideoStream/resources/libgui/webgui.py", line 226, in __init__
    BaseHTTPRequestHandler.__init__(self, *args)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```
`

**Comment by ddurdle** [comment]
not an issue.
