### ISSUE TITLE
How to set up plex  

### ISSUE THREAD

**Issue by Saitama-san** [ddurdle/GoogleDrive-VideoStream_extra#4]
I am using this on emby, but I saw under transcoders folders PlexTranscoder.pl.

Does that means I can use this on plex?

If yes, can you please write here steps how to do that or send me a message

**Comment by bnichs5** [comment]
I second this. I would also like to use this for plex.

**Comment by ddurdle** [comment]
Sorry, plex is a work-in-process and not available public use.
